on:
  push:
    tags:
      - '*'

jobs:
  publish-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display tag name
        run : echo ${{ github.event.release.tag_name }}
    
      # - name: Build and push monocle_backend Docker image
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: changemetrics/monocle_backend
      #     tags: ${{ github.event.release.tag_name }}
    
      # - name: Build and push monocle_web Docker image
      #   uses: docker/build-push-action@v1
      #   with:
      #     path: web
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: changemetrics/monocle_backend
      #     tags: ${{ github.event.release.tag_name }}
